import { Namespace } from "../../../data/storage/Namespaces";
import { UseCase } from "../../common/entities/UseCase";
import { DynamicRepositoryFactory } from "../../common/factories/DynamicRepositoryFactory";
import { Instance } from "../../instance/entities/Instance";
import { MetadataModule } from "../entities/MetadataModule";
import { BaseModule, Module } from "../entities/Module";

export class ListModulesUseCase implements UseCase {
    constructor(private repositoryFactory: DynamicRepositoryFactory, private localInstance: Instance) {}

    public async execute(
        bypassSharingSettings = false,
        instance = this.localInstance,
        includeAutogenerated = false
    ): Promise<Module[]> {
        const storageClient = await this.repositoryFactory.configRepository(instance).getStorageClientPromise();

        const { userGroups } = await this.repositoryFactory.userRepository(this.localInstance).getCurrent();
        const { id: userId } = await this.repositoryFactory.userRepository(this.localInstance).getCurrent();

        const data = (await storageClient.listObjectsInCollection<BaseModule>(Namespace.MODULES)).filter(
            module => includeAutogenerated || !module.autogenerated
        );

        const isRemoteInstance = instance !== this.localInstance;

        return data
            .map(module => {
                switch (module.type) {
                    case "metadata":
                        return MetadataModule.build(module);
                    default:
                        throw new Error("Unknown module");
                }
            })
            .filter(
                module => bypassSharingSettings || isRemoteInstance || module.hasPermissions("read", userId, userGroups)
            );
    }
}
